name: CI
on:
    push:
        branches:
            - afconvert

jobs:
  macos:
    runs-on: macos-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3
      - name: xcrun
        run: |
          xcrun --sdk macosx --show-sdk-path
      - name: Convert
        run: |
          afconvert -f m4af -d aac -b 80000 -s 0 -q 96 Aeterna.flac Aeterna.m4a

      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist-results
          path: |
            *.caf
            *.m4a
