name: CI
on:
    push:
        branches:
            - afconvert

jobs:
  macos:
    runs-on: macos-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3
      - name: xcrun
        run: |
          xcrun --sdk macosx --show-sdk-path
      - name: Convert
        run: |
          afconvert -f caff -d BEI16 -l Mono 1ch.aif mono.caf
          afconvert -f caff -d BEI16 -l AC3_1_0_1 1.1ch-FC-LF.wav 1.1ch_AC3_1_0_1.caf
          afconvert -f caff -d BEI16 -l AC3_1_0_1 2.1ch-FL-FR-LF.wav 2.1ch_DVD_4.caf
          afconvert -f caff -d BEI16 -l MPEG_3_0_A 3ch-L-C-R.aif 3ch_MPEG_3_0_A.caf
          afconvert -f caff -d BEI16 -l AC3_3_0 3ch-L-C-R.aif 3ch_AC3_3_0.caf
          afconvert -f caff -d BEI16 -l MPEG_3_0_B 3ch-L-C-R.aif 3ch_MPEG_3_0_B.caf
          afconvert -f caff -d BEI16 -l ITU_2_1 3ch_FL-FR-BC.wav 3ch_ITU_2_1.caf

      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist-results
          path: |
            *.caf
