name: CI

on:
    push:
        branches:
            - qaac

jobs:
    build:
        strategy:
            matrix:
                platform: [Win32, x64]
        runs-on: windows-latest
        env:
            ACTIONS_ALLOW_UNSECURE_COMMANDS: true
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            - name: Add MSBuild to PATH
              uses: microsoft/setup-msbuild@v2
            - name: Build
              run: |
                  MSBuild.exe vcproject/qaac.sln /m /p:Configuration=Release /p:Platform=${{ matrix.platform }}
